# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45c143bb20f16e87ecf8fca724509281f17cab2190f9ec520b8879ba860c3c099ffab8fbb4b81ef90f7620a008700940a4fbe3befefabfbba852d799ba6ea617

test:
  secret_key_base: e1fdea2dd1fcd40a04b15e24189bdd512f9e80f99decab4431349aca75a3b5c6ca3ab45ed1d85cb0f251858f288bfed49606b6ebf1d4a30e8fce624db256fef2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
